using System.Collections.Generic;

public class Datum
{
    public string Name { get; set; } = string.Empty;
    public string Measure { get; set; } = string.Empty;
    public string Type { get; set; } = "FLOAT32";
}
public class MeasurementUnits
{
    public Dictionary<string, string> UnitsByName { get; }

    public Datum FindUnitByName(string name)
    {
        if (UnitsByName.TryGetValue(name, out var unit))
        {
            return new Datum
            {
                Name = name,
                Measure = unit,
                Type = "FLOAT32"
            };
        }

        throw new KeyNotFoundException($"Measurement unit '{name}' not found in UnitsByName.");
    }

    public MeasurementUnits()
    {
        UnitsByName = new Dictionary<string, string>
        {
        { "NONE", "" },
        { "ACCELERATION BODY X", "Feet per second squared" },
        { "ACCELERATION BODY Y", "Feet per second squared" },
        { "ACCELERATION BODY Z", "Feet per second squared" },
        { "ACCELERATION WORLD X", "Feet per second squared" },
        { "ACCELERATION WORLD Y", "Feet per second squared" },
        { "ACCELERATION WORLD Z", "Feet per second squared" },
        { "ADF ACTIVE FREQUENCY", "Frequency ADF BCD32" },
        { "ADF AVAILABLE", "Bool" },
        { "ADF CARD", "Degrees" },
        { "ADF DISTANCE", "Meters" },
        { "ADF EXT FREQUENCY", "Frequency BCD16" },
        { "ADF FREQUENCY", "Frequency BCD16" },
        { "ADF IDENT", "String" },
        { "ADF LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "ADF NAME", "String" },
        { "ADF RADIAL", "Degrees" },
        { "ADF RADIAL MAG", "Degrees" },
        { "ADF SIGNAL", "Number" },
        { "ADF SOUND", "Bool" },
        { "ADF STANDBY AVAILABLE", "Bool" },
        { "ADF STANDBY FREQUENCY", "Hz" },
        { "ADF VOLUME", "" },
        { "AILERON AVERAGE DEFLECTION", "Radians" },
        { "AILERON LEFT DEFLECTION", "Radians" },
        { "AILERON LEFT DEFLECTION PCT", "Percent Over 100" },
        { "AILERON POSITION", "Position (-16K to 0) -16K = full left" },
        { "AILERON RIGHT DEFLECTION", "Radians" },
        { "AILERON RIGHT DEFLECTION PCT", "Percent Over 100" },
        { "AILERON TRIM", "Radians" },
        { "AILERON TRIM DISABLED", "Bool" },
        { "AILERON TRIM PCT", "Float. Percent over 100" },
        { "AIRCRAFT WIND X", "Knots" },
        { "AIRCRAFT WIND Y", "Knots" },
        { "AIRCRAFT WIND Z", "Knots" },
        { "AIRSPEED BARBER POLE", "Knots" },
        { "AIRSPEED EQUIVALENT", "Knots" },
        { "AIRSPEED INDICATED", "Knots" },
        { "AIRSPEED MACH", "Mach" },
        { "AIRSPEED SELECT INDICATED OR TRUE", "Knots" },
        { "AIRSPEED TRUE", "Knots" },
        { "AIRSPEED TRUE CALIBRATE", "Degrees" },
        { "AIRSPEED TRUE RAW", "" },
        { "AI ANTISTALL STATE", "" },
        { "AI AUTOTRIM ACTIVE", "" },
        { "AI AUTOTRIM ACTIVE AGAINST PLAYER", "" },
        { "AI CONTROLS", "" },
        { "AI CURSOR MODE ACTIVE", "" },
        { "ALTERNATE STATIC SOURCE OPEN", "Bool" },
        { "ALTERNATOR BREAKER PULLED", "" },
        { "ALTERNATOR CONNECTION ON", "" },
        { "AMBIENT DENSITY", "Slugs per cubic feet" },
        { "AMBIENT IN CLOUD", "Bool" },
        { "AMBIENT PRECIP RATE", "" },
        { "AMBIENT PRECIP STATE", "Mask" },
        { "AMBIENT PRESSURE", "Inches of mercury, inHg" },
        { "AMBIENT TEMPERATURE", "Celsius" },
        { "AMBIENT VISIBILITY", "Meters" },
        { "AMBIENT WIND DIRECTION", "Degrees" },
        { "AMBIENT WIND VELOCITY", "Knots" },
        { "AMBIENT WIND X", "Meters per second" },
        { "AMBIENT WIND Y", "Meters per second" },
        { "AMBIENT WIND Z", "Meters per second" },
        { "ANEMOMETER PCT RPM", "Percent over 100" },
        { "ANGLE OF ATTACK INDICATOR", "Radians" },
        { "ANIMATION DELTA TIME", "Seconds" },
        { "ANNUNCIATOR SWITCH", "Bool" },
        { "ANTISKID BRAKES ACTIVE", "Bool" },
        { "APPLY HEAT TO SYSTEMS", "Bool" },
        { "APU BLEED PRESSURE RECEIVED BY ENGINE", "" },
        { "APU GENERATOR ACTIVE", "Bool" },
        { "APU GENERATOR SWITCH", "Bool" },
        { "APU ON FIRE DETECTED", "Bool" },
        { "APU PCT RPM", "Percent over 100" },
        { "APU PCT STARTER", "Percent over 100" },
        { "APU SWITCH", "" },
        { "APU VOLTS", "Volts" },
        { "ARTIFICIAL GROUND ELEVATION", "Feet" },
        { "ASSISTANCE LANDING ENABLED", "" },
        { "ASSISTANCE TAKEOFF ENABLED", "" },
        { "ATC AIRLINE", "String (50)" },
        { "ATC AIRPORT IS TOWERED", "Bool" },
        { "ATC CLEARED IFR", "" },
        { "ATC CLEARED LANDING", "Bool" },
        { "ATC CLEARED TAKEOFF", "Bool" },
        { "ATC CLEARED TAXI", "Bool" },
        { "ATC CURRENT WAYPOINT ALTITUDE", "" },
        { "ATC FLIGHTPLAN DIFF ALT", "" },
        { "ATC FLIGHTPLAN DIFF DISTANCE", "" },
        { "ATC FLIGHTPLAN DIFF HEADING", "" },
        { "ATC FLIGHT NUMBER", "String (6)" },
        { "ATC HEAVY", "Bool" },
        { "ATC ID", "String (10)" },
        { "ATC IFR FP TO REQUEST", "" },
        { "ATC MODEL", "String (10)" },
        { "ATC ON PARKING SPOT", "Bool" },
        { "ATC PREVIOUS WAYPOINT ALTITUDE", "" },
        { "ATC RUNWAY AIRPORT NAME", "String" },
        { "ATC RUNWAY DISTANCE", "Meters" },
        { "ATC RUNWAY END DISTANCE", "Meters" },
        { "ATC RUNWAY HEADING DEGREES TRUE", "Degrees" },
        { "ATC RUNWAY LENGTH", "Meters" },
        { "ATC RUNWAY RELATIVE POSITION X", "Meters" },
        { "ATC RUNWAY RELATIVE POSITION Y", "Meters" },
        { "ATC RUNWAY RELATIVE POSITION Z", "Meters" },
        { "ATC RUNWAY SELECTED", "Bool" },
        { "ATC RUNWAY START DISTANCE", "Meters" },
        { "ATC RUNWAY TDPOINT RELATIVE POSITION X", "Meters" },
        { "ATC RUNWAY TDPOINT RELATIVE POSITION Y", "Meters" },
        { "ATC RUNWAY TDPOINT RELATIVE POSITION Z", "Meters" },
        { "ATC RUNWAY WIDTH", "Meters" },
        { "ATC SUGGESTED MIN RWY LANDING", "Feet" },
        { "ATC SUGGESTED MIN RWY TAKEOFF", "Feet" },
        { "ATC TAXIPATH DISTANCE", "" },
        { "ATC TYPE", "String (30)" },
        { "ATTITUDE BARS POSITION", "Percent Over 100" },
        { "ATTITUDE CAGE", "Bool" },
        { "ATTITUDE INDICATOR BANK DEGREES", "Radians" },
        { "ATTITUDE INDICATOR PITCH DEGREES", "Radians" },
        { "AUDIO PANEL AVAILABLE", "Bool" },
        { "AUDIO PANEL VOLUME", "Float, Percent." },
        { "AUTOBRAKES ACTIVE", "Bool" },
        { "AUTOPILOT AIRSPEED ACQUISITION", "" },
        { "AUTOPILOT AIRSPEED HOLD", "Bool" },
        { "AUTOPILOT AIRSPEED HOLD CURRENT", "" },
        { "AUTOPILOT AIRSPEED HOLD VAR", "Knots" },
        { "AUTOPILOT AIRSPEED MAX CALCULATED", "" },
        { "AUTOPILOT AIRSPEED MIN CALCULATED", "" },
        { "AUTOPILOT ALTITUDE ARM", "" },
        { "AUTOPILOT ALTITUDE LOCK", "Bool" },
        { "AUTOPILOT ALTITUDE LOCK VAR", "Feet" },
        { "AUTOPILOT ALTITUDE MANUALLY TUNABLE", "" },
        { "AUTOPILOT ALTITUDE SLOT INDEX", "Number" },
        { "AUTOPILOT ALT RADIO MODE", "Bool" },
        { "AUTOPILOT APPROACH ACTIVE", "" },
        { "AUTOPILOT APPROACH ARM", "" },
        { "AUTOPILOT APPROACH CAPTURED", "" },
        { "AUTOPILOT APPROACH HOLD", "Bool" },
        { "AUTOPILOT APPROACH IS LOCALIZER", "" },
        { "AUTOPILOT ATTITUDE HOLD", "Bool" },
        { "AUTOPILOT AVAILABLE", "Bool" },
        { "AUTOPILOT AVIONICS MANAGED", "Bool" },
        { "AUTOPILOT BACKCOURSE HOLD", "Bool" },
        { "AUTOPILOT BANK HOLD", "Bool" },
        { "AUTOPILOT BANK HOLD REF", "Radians" },
        { "AUTOPILOT CRUISE SPEED HOLD", "" },
        { "AUTOPILOT DEFAULT PITCH MODE", "Enum" },
        { "AUTOPILOT DEFAULT ROLL MODE", "Enum" },
        { "AUTOPILOT DISENGAGED", "Bool" },
        { "AUTOPILOT FLIGHT DIRECTOR ACTIVE", "Bool" },
        { "AUTOPILOT FLIGHT DIRECTOR BANK", "Radians" },
        { "AUTOPILOT FLIGHT DIRECTOR BANK EX1", "Radians" },
        { "AUTOPILOT FLIGHT DIRECTOR PITCH", "Radians" },
        { "AUTOPILOT FLIGHT DIRECTOR PITCH EX1", "Radians" },
        { "AUTOPILOT FLIGHT LEVEL CHANGE", "" },
        { "AUTOPILOT GLIDESLOPE ACTIVE", "" },
        { "AUTOPILOT GLIDESLOPE ARM", "" },
        { "AUTOPILOT GLIDESLOPE HOLD", "Bool" },
        { "AUTOPILOT HEADING LOCK", "Bool" },
        { "AUTOPILOT HEADING LOCK DIR", "Degrees" },
        { "AUTOPILOT HEADING MANUALLY TUNABLE", "" },
        { "AUTOPILOT HEADING SLOT INDEX", "Number" },
        { "AUTOPILOT MACH HOLD", "Bool" },
        { "AUTOPILOT MACH HOLD VAR", "Number" },
        { "AUTOPILOT MANAGED INDEX", "Number" },
        { "AUTOPILOT MANAGED SPEED IN MACH", "Bool" },
        { "AUTOPILOT MANAGED THROTTLE ACTIVE", "Bool" },
        { "AUTOPILOT MASTER", "Bool" },
        { "AUTOPILOT MAX BANK", "Radians" },
        { "AUTOPILOT MAX BANK ID", "" },
        { "AUTOPILOT MAX BANK VELOCITY", "Radians" },
        { "AUTOPILOT MAX SPEED HOLD", "" },
        { "AUTOPILOT NAV1 LOCK", "Bool" },
        { "AUTOPILOT NAV SELECTED", "Number" },
        { "AUTOPILOT PITCH HOLD", "Bool" },
        { "AUTOPILOT PITCH HOLD REF", "Radians" },
        { "AUTOPILOT RPM HOLD", "Bool" },
        { "AUTOPILOT RPM HOLD VAR", "Number" },
        { "AUTOPILOT RPM SLOT INDEX", "Number" },
        { "AUTOPILOT SPEED SETTING", "" },
        { "AUTOPILOT SPEED SLOT INDEX", "Number" },
        { "AUTOPILOT TAKEOFF POWER ACTIVE", "Bool" },
        { "AUTOPILOT THROTTLE ARM", "Bool" },
        { "AUTOPILOT THROTTLE MAX THRUST", "Float, Percent." },
        { "AUTOPILOT VERTICAL HOLD", "Bool" },
        { "AUTOPILOT VERTICAL HOLD VAR", "Feet/minute" },
        { "AUTOPILOT VS SLOT INDEX", "Number" },
        { "AUTOPILOT WING LEVELER", "Bool" },
        { "AUTOPILOT YAW DAMPER", "Bool" },
        { "AUTOTHROTTLE ACTIVE", "Bool" },
        { "AUTO BRAKE SWITCH CB", "Number" },
        { "AUTO COORDINATION", "Bool" },
        { "AUX WHEEL ROTATION ANGLE", "Radians" },
        { "AUX WHEEL RPM", "Rpm" },
        { "AVIONICS MASTER SWITCH", "Bool" },
        { "BAGGAGELOADER ANGLE CURRENT", "Degrees" },
        { "BAGGAGELOADER ANGLE TARGET", "Degrees" },
        { "BAGGAGELOADER END RAMP Y", "Meters" },
        { "BAGGAGELOADER END RAMP Z", "Meters" },
        { "BAGGAGELOADER PIVOT Y", "Meters" },
        { "BAGGAGELOADER PIVOT Z", "Meters" },
        { "BARBER POLE MACH", "Mach" },
        { "BAROMETER PRESSURE", "Millibars" },
        { "BATTERY BREAKER PULLED", "" },
        { "BATTERY CONNECTION ON", "" },
        { "BETA DOT", "Radians per second" },
        { "BLAST SHIELD POSITION", "Percent_over_100" },
        { "BLEED AIR APU", "" },
        { "BLEED AIR ENGINE", "" },
        { "BLEED AIR SOURCE CONTROL", "Enum" },
        { "BOARDINGRAMP ELEVATION CURRENT", "Meters" },
        { "BOARDINGRAMP ELEVATION TARGET", "Meters" },
        { "BOARDINGRAMP END POSITION Y", "Meters" },
        { "BOARDINGRAMP END POSITION Z", "Meters" },
        { "BOARDINGRAMP ORIENTATION CURRENT", "Percent over 100" },
        { "BOARDINGRAMP ORIENTATION TARGET", "Percent over 100" },
        { "BOARDINGRAMP START POSITION Y", "Meters" },
        { "BOARDINGRAMP START POSITION Z", "Meters" },
        { "BOMB AMMO", "" },
        { "BRAKE DEPENDENT HYDRAULIC PRESSURE", "Pounds per square foot" },
        { "BRAKE INDICATOR", "Position (0 to 16K) 0 = off, 16K full" },
        { "BRAKE LEFT POSITION", "Position (0 to 32K) 0 = off, 32K full" },
        { "BRAKE LEFT POSITION EX1", "Position (0 to 32K) 0 = off, 32K full" },
        { "BRAKE PARKING INDICATOR", "Bool" },
        { "BRAKE PARKING POSITION", "Position (0 to 32K) 0 = off, 32K full" },
        { "BRAKE RIGHT POSITION", "Position (0 to 32K) 0 = off, 32K full" },
        { "BRAKE RIGHT POSITION EX1", "Position (0 to 32K) 0 = off, 32K full" },
        { "BREAKER ADF", "" },
        { "BREAKER ALTFLD", "" },
        { "BREAKER AUTOPILOT", "" },
        { "BREAKER AVNBUS1", "" },
        { "BREAKER AVNBUS2", "" },
        { "BREAKER AVNFAN", "" },
        { "BREAKER FLAP", "" },
        { "BREAKER GPS", "" },
        { "BREAKER INST", "" },
        { "BREAKER INSTLTS", "" },
        { "BREAKER LTS PWR", "" },
        { "BREAKER NAVCOM1", "" },
        { "BREAKER NAVCOM2", "" },
        { "BREAKER NAVCOM3", "" },
        { "BREAKER TURNCOORD", "" },
        { "BREAKER WARN", "" },
        { "BREAKER XPNDR", "" },
        { "BUS BREAKER PULLED", "" },
        { "BUS CONNECTION ON", "" },
        { "BUS LOOKUP INDEX", "" },
        { "CABIN NO SMOKING ALERT SWITCH", "Bool" },
        { "CABIN SEATBELTS ALERT SWITCH", "Bool" },
        { "CABLE CAUGHT BY TAILHOOK", "Number" },
        { "CAMERA ACTION COCKPIT VIEW RESET", "" },
        { "CAMERA ACTION COCKPIT VIEW SAVE", "" },
        { "CAMERA GAMEPLAY PITCH YAW", "" },
        { "CAMERA REQUEST ACTION", "" },
        { "CAMERA STATE", "" },
        { "CAMERA SUBSTATE", "" },
        { "CAMERA VIEW TYPE AND INDEX", "" },
        { "CAMERA VIEW TYPE AND INDEX MAX", "" },
        { "CANNON AMMO", "" },
        { "CANOPY OPEN", "Percent Over 100" },
        { "CARB HEAT AVAILABLE", "Bool" },
        { "CATAPULT STROKE POSITION", "Number" },
        { "CATEGORY", "String" },
        { "CATERINGTRUCK AIRCRAFT DOOR CONTACT OFFSET Z", "Meters" },
        { "CATERINGTRUCK ELEVATION CURRENT", "Meters" },
        { "CATERINGTRUCK ELEVATION TARGET", "Meters" },
        { "CATERINGTRUCK OPENING CURRENT", "Percent over 100" },
        { "CATERINGTRUCK OPENING TARGET", "Percent over 100" },
        { "CENTER WHEEL ROTATION ANGLE", "Radians" },
        { "CENTER WHEEL RPM", "Rpm" },
        { "CG AFT LIMIT", "Percent over 100" },
        { "CG FWD LIMIT", "Percent over 100" },
        { "CG MAX MACH", "Machs" },
        { "CG MIN MACH", "Machs" },
        { "CG PERCENT", "Percent over 100" },
        { "CG PERCENT LATERAL", "Percent over 100" },
        { "CHASE CAMERA HEADLOOK", "" },
        { "CHASE CAMERA MOMENTUM", "" },
        { "CHASE CAMERA SPEED", "" },
        { "CHASE CAMERA ZOOM", "" },
        { "CHASE CAMERA ZOOM SPEED", "" },
        { "CIRCUIT AUTOPILOT ON", "Bool" },
        { "CIRCUIT AUTO BRAKES ON", "Bool" },
        { "CIRCUIT AUTO FEATHER ON", "Bool" },
        { "CIRCUIT AVIONICS ON", "Bool" },
        { "CIRCUIT BREAKER PULLED", "" },
        { "CIRCUIT COM ON", "Bool" },
        { "CIRCUIT CONNECTION ON", "" },
        { "CIRCUIT FLAP MOTOR ON", "Bool" },
        { "CIRCUIT GEAR MOTOR ON", "Bool" },
        { "CIRCUIT GEAR WARNING ON", "Bool" },
        { "CIRCUIT GENERAL PANEL ON", "Bool" },
        { "CIRCUIT HYDRAULIC PUMP ON", "Bool" },
        { "CIRCUIT MARKER BEACON ON", "Bool" },
        { "CIRCUIT NAVCOM1 ON", "" },
        { "CIRCUIT NAVCOM2 ON", "" },
        { "CIRCUIT NAVCOM3 ON", "" },
        { "CIRCUIT NAV ON", "Bool" },
        { "CIRCUIT ON", "" },
        { "CIRCUIT PITOT HEAT ON", "Bool" },
        { "CIRCUIT POWER SETTING", "" },
        { "CIRCUIT PROP SYNC ON", "Bool" },
        { "CIRCUIT STANDBY VACUUM ON", "" },
        { "CIRCUIT STANDY VACUUM ON", "Bool" },
        { "CIRCUIT SWITCH ON", "" },
        { "COCKPIT CAMERA HEADLOOK", "" },
        { "COCKPIT CAMERA HEIGHT", "" },
        { "COCKPIT CAMERA INSTRUMENT AUTOSELECT", "" },
        { "COCKPIT CAMERA MOMENTUM", "" },
        { "COCKPIT CAMERA SIDE", "" },
        { "COCKPIT CAMERA SPEED", "" },
        { "COCKPIT CAMERA UPPER POSITION", "" },
        { "COCKPIT CAMERA ZOOM", "" },
        { "COCKPIT CAMERA ZOOM SPEED", "" },
        { "COLLECTIVE POSITION", "Percent_over_100" },
        { "COM1 STORED FREQUENCY", "" },
        { "COM2 STORED FREQUENCY", "" },
        { "COM3 STORED FREQUENCY", "" },
        { "COM ACTIVE BEARING", "Degrees" },
        { "COM ACTIVE DISTANCE", "Meters" },
        { "COM ACTIVE FREQUENCY", "Frequency BCD16" },
        { "COM ACTIVE FREQ IDENT", "String" },
        { "COM ACTIVE FREQ NAME", "String" },
        { "COM ACTIVE FREQ TYPE", "String" },
        { "COM ACTIVE LATLONALT", "LLA structure" },
        { "COM AVAILABLE", "Bool" },
        { "COM LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "COM RECEIVE", "" },
        { "COM RECEIVE ALL", "Bool" },
        { "COM RECEIVE EX1", "" },
        { "COM RECIEVE ALL", "Bool" },
        { "COM SPACING MODE", "Enum" },
        { "COM STANDBY FREQUENCY", "Frequency BCD16" },
        { "COM STANDBY FREQ IDENT", "String" },
        { "COM STANDBY FREQ NAME", "String" },
        { "COM STANDBY FREQ TYPE", "String" },
        { "COM STATUS", "Enum" },
        { "COM TEST", "Bool" },
        { "COM TRANSMIT", "Bool" },
        { "COM VOLUME", "" },
        { "CONCORDE NOSE ANGLE", "Radians" },
        { "CONCORDE VISOR NOSE HANDLE", "Enum" },
        { "CONCORDE VISOR POSITION PERCENT", "Percent over 100" },
        { "CONTACT POINT COMPRESSION", "Percent Over 100" },
        { "CONTACT POINT IS ON GROUND", "bool" },
        { "CONTACT POINT IS SKIDDING", "bool" },
        { "CONTACT POINT POSITION", "Percent Over 100" },
        { "CONTACT POINT SKIDDING FACTOR", "Percent Over 100" },
        { "CONTACT POINT WATER DEPTH", "Feet" },
        { "CONTRAILS CONDITIONS MET", "Bool" },
        { "CONTROLLABLE", "" },
        { "COPILOT TRANSMITTER TYPE", "Enum" },
        { "COPILOT TRANSMITTING", "Bool" },
        { "COWL FLAPS", "" },
        { "CRASH FLAG", "Enum" },
        { "CRASH SEQUENCE", "Enum" },
        { "DECISION ALTITUDE MSL", "Feet" },
        { "DECISION HEIGHT", "Feet" },
        { "DELEGATE CONTROLS TO AI", "" },
        { "DELTA HEADING RATE", "Radians per second" },
        { "DESIGN CRUISE ALT", "" },
        { "DESIGN SPAWN ALTITUDE CRUISE", "" },
        { "DESIGN SPAWN ALTITUDE DESCENT", "" },
        { "DESIGN SPEED CLIMB", "" },
        { "DESIGN SPEED MIN ROTATION", "" },
        { "DESIGN SPEED VC", "Feet per second" },
        { "DESIGN SPEED VS0", "Feet per second" },
        { "DESIGN SPEED VS1", "Feet per second" },
        { "DESIGN TAKEOFF SPEED", "" },
        { "DISK BANK ANGLE", "Radians" },
        { "DISK BANK PCT", "Percent over 100" },
        { "DISK CONING PCT", "Percent over 100" },
        { "DISK PITCH ANGLE", "Radians" },
        { "DISK PITCH PCT", "Percent over 100" },
        { "DME SOUND", "Bool" },
        { "DRONE CAMERA FOCUS", "" },
        { "DRONE CAMERA FOCUS MODE", "" },
        { "DRONE CAMERA FOLLOW", "" },
        { "DRONE CAMERA FOV", "" },
        { "DRONE CAMERA LOCKED", "" },
        { "DRONE CAMERA SPEED ROTATION", "" },
        { "DRONE CAMERA SPEED TRAVELLING", "" },
        { "DROPPABLE OBJECTS COUNT", "Number" },
        { "DROPPABLE OBJECTS TYPE", "String" },
        { "DROPPABLE OBJECTS UI NAME", "String" },
        { "DYNAMIC PRESSURE", "Pounds per square foot" },
        { "ELECTRICAL AVIONICS BUS AMPS", "Amperes" },
        { "ELECTRICAL AVIONICS BUS VOLTAGE", "Volts" },
        { "ELECTRICAL BATTERY BUS AMPS", "Amperes" },
        { "ELECTRICAL BATTERY BUS VOLTAGE", "Volts" },
        { "ELECTRICAL BATTERY ESTIMATED CAPACITY PCT", "Percent Over 100" },
        { "ELECTRICAL BATTERY LOAD", "Amperes" },
        { "ELECTRICAL BATTERY VOLTAGE", "Volts" },
        { "ELECTRICAL GENALT BUS AMPS", "Amperes" },
        { "ELECTRICAL GENALT BUS VOLTAGE", "Volts" },
        { "ELECTRICAL GENALT LOAD", "" },
        { "ELECTRICAL HOT BATTERY BUS AMPS", "Amperes" },
        { "ELECTRICAL HOT BATTERY BUS VOLTAGE", "Volts" },
        { "ELECTRICAL MAIN BUS AMPS", "Amperes" },
        { "ELECTRICAL MAIN BUS VOLTAGE", "Volts" },
        { "ELECTRICAL MASTER BATTERY", "Bool" },
        { "ELECTRICAL OLD CHARGING AMPS", "Amps" },
        { "ELECTRICAL TOTAL LOAD AMPS", "Amperes" },
        { "ELEVATOR DEFLECTION", "Radians" },
        { "ELEVATOR DEFLECTION PCT", "Percent Over 100" },
        { "ELEVATOR POSITION", "Position (-16K to 0) -16K = full down" },
        { "ELEVATOR TRIM DISABLED", "Bool" },
        { "ELEVATOR TRIM DOWN LIMIT", "Radians" },
        { "ELEVATOR TRIM INDICATOR", "Position (-16K to 0) -16K = full down" },
        { "ELEVATOR TRIM NEUTRAL", "Radians" },
        { "ELEVATOR TRIM PCT", "Percent Over 100" },
        { "ELEVATOR TRIM POSITION", "Radians" },
        { "ELEVATOR TRIM UP LIMIT", "Radians" },
        { "ELEVON DEFLECTION", "Radians" },
        { "ELT ACTIVATED", "" },
        { "EMPTY WEIGHT", "Pounds" },
        { "EMPTY WEIGHT CROSS COUPLED MOI", "Slugs per feet squared" },
        { "EMPTY WEIGHT PITCH MOI", "Slugs per feet squared" },
        { "EMPTY WEIGHT ROLL MOI", "Slugs per feet squared" },
        { "EMPTY WEIGHT YAW MOI", "Slugs per feet squared" },
        { "ENGINE CONTROL SELECT", "Mask" },
        { "ENGINE MIXURE AVAILABLE", "Bool" },
        { "ENGINE PRIMER", "" },
        { "ENGINE TYPE", "Enum" },
        { "ENG ANTI ICE", "Bool" },
        { "ENG COMBUSTION", "Bool" },
        { "ENG CYLINDER HEAD TEMPERATURE", "Rankine" },
        { "ENG ELECTRICAL LOAD", "Percent scalar 16K (Max load * 16384)" },
        { "ENG EXHAUST GAS TEMPERATURE", "Rankine" },
        { "ENG EXHAUST GAS TEMPERATURE GES", "Percent over 100" },
        { "ENG FAILED", "Number" },
        { "ENG FUEL FLOW BUG POSITION", "Pounds per hour" },
        { "ENG FUEL FLOW GPH", "Gallons per hour" },
        { "ENG FUEL FLOW PPH", "Pounds per hour" },
        { "ENG FUEL FLOW PPH SSL", "" },
        { "ENG FUEL PRESSURE", "PSI scalar 16K (Psi * 16384)" },
        { "ENG HYDRAULIC PRESSURE", "Pounds per square foot" },
        { "ENG HYDRAULIC QUANTITY", "Percent over 100" },
        { "ENG MANIFOLD PRESSURE", "inHG." },
        { "ENG MAX RPM", "Rpm" },
        { "ENG N1 RPM", "Rpm (0 to 16384 = 0 to 100%)" },
        { "ENG N2 RPM", "Rpm(0 to 16384 = 0 to 100%)" },
        { "ENG OIL PRESSURE", "Pounds per square foot" },
        { "ENG OIL QUANTITY", "Percent over 100" },
        { "ENG OIL TEMPERATURE", "Rankine" },
        { "ENG ON FIRE", "Bool" },
        { "ENG PRESSURE RATIO", "Ratio (0-16384)" },
        { "ENG PRESSURE RATIO GES", "" },
        { "ENG ROTOR RPM", "Percent scalar 16K (Max rpm * 16384)" },
        { "ENG RPM ANIMATION PERCENT", "Percent" },
        { "ENG RPM SCALER", "Scalar" },
        { "ENG TORQUE", "Foot pounds" },
        { "ENG TORQUE PERCENT", "Percent scalar 16K (Ft/lbs * 16384)" },
        { "ENG TRANSMISSION PRESSURE", "PSI scalar 16K (Psi * 16384)" },
        { "ENG TRANSMISSION TEMPERATURE", "Celsius scalar 16K (Degrees * 16384)" },
        { "ENG TURBINE TEMPERATURE", "Celsius scalar 16K (degrees * 16384)" },
        { "ENG VIBRATION", "Number" },
        { "ENV CLOUD DENSITY", "UNITS_PERCENT" },
        { "ESTIMATED CRUISE SPEED", "Feet per second" },
        { "ESTIMATED FUEL FLOW", "Pounds per hour" },
        { "EXIT OPEN", "Percent Over 100" },
        { "EXIT POSX", "Feet" },
        { "EXIT POSY", "Feet" },
        { "EXIT POSZ", "Feet" },
        { "EXIT TYPE", "Enum" },
        { "EXTERNAL POWER AVAILABLE", "" },
        { "EXTERNAL POWER BREAKER PULLED", "" },
        { "EXTERNAL POWER CONNECTION ON", "" },
        { "EXTERNAL POWER ON", "" },
        { "EXTERNAL SYSTEM VALUE", "" },
        { "EYEPOINT POSITION", "`SIMCONNECT_DATA_XYZ` structure, feet" },
        { "FIRE BOTTLE DISCHARGED", "Bool" },
        { "FIRE BOTTLE SWITCH", "Bool" },
        { "FLAPS AVAILABLE", "Bool" },
        { "FLAPS EFFECTIVE HANDLE INDEX", "Number" },
        { "FLAPS HANDLE INDEX", "Number" },
        { "FLAPS HANDLE PERCENT", "Percent Over 100" },
        { "FLAPS NUM HANDLE POSITIONS", "Number" },
        { "FLAP DAMAGE BY SPEED", "Bool" },
        { "FLAP POSITION SET", "" },
        { "FLAP SPEED EXCEEDED", "Bool" },
        { "FLOLS HEIGHT", "Percent" },
        { "FLY ASSISTANT CANCEL DESTINATION", "" },
        { "FLY ASSISTANT CANCEL DESTINATION DISPLAY", "" },
        { "FLY ASSISTANT COM AI LOCKED", "" },
        { "FLY ASSISTANT HAVE DESTINATION", "" },
        { "FLY ASSISTANT LANDING SPEED", "" },
        { "FLY ASSISTANT LANDING SPEED DISPLAY MODE", "" },
        { "FLY ASSISTANT NEAREST CATEGORY", "" },
        { "FLY ASSISTANT NEAREST COUNT", "" },
        { "FLY ASSISTANT NEAREST METADATA", "" },
        { "FLY ASSISTANT NEAREST NAME", "" },
        { "FLY ASSISTANT NEAREST SELECTED", "" },
        { "FLY ASSISTANT RIBBONS ACTIVE", "" },
        { "FLY ASSISTANT SET AS DESTINATION", "" },
        { "FLY ASSISTANT STALL SPEED", "" },
        { "FLY ASSISTANT STALL SPEED DISPLAY MODE", "" },
        { "FLY ASSISTANT TAKEOFF SPEED", "" },
        { "FLY ASSISTANT TAKEOFF SPEED DISPLAY MODE", "" },
        { "FLY ASSISTANT TAKEOFF SPEED ESTIMATED", "" },
        { "FLY BY WIRE ALPHA PROTECTION", "" },
        { "FLY BY WIRE ELAC FAILED", "Bool" },
        { "FLY BY WIRE ELAC SWITCH", "Bool" },
        { "FLY BY WIRE FAC FAILED", "Bool" },
        { "FLY BY WIRE FAC SWITCH", "Bool" },
        { "FLY BY WIRE SEC FAILED", "Bool" },
        { "FLY BY WIRE SEC SWITCH", "Bool" },
        { "FOLDING WING HANDLE POSITION", "Bool" },
        { "FOLDING WING LEFT PERCENT", "Percent Over 100" },
        { "FOLDING WING RIGHT PERCENT", "Percent Over 100" },
        { "FUELSYSTEM ENGINE PRESSURE", "" },
        { "FUELSYSTEM JUNCTION SETTING", "" },
        { "FUELSYSTEM LINE FUEL FLOW", "" },
        { "FUELSYSTEM LINE FUEL LEVEL", "" },
        { "FUELSYSTEM LINE FUEL PRESSURE", "" },
        { "FUELSYSTEM PUMP ACTIVE", "" },
        { "FUELSYSTEM PUMP SWITCH", "" },
        { "FUELSYSTEM TANK CAPACITY", "Gallons" },
        { "FUELSYSTEM TANK LEVEL", "Percent over 100" },
        { "FUELSYSTEM TANK QUANTITY", "Gallons" },
        { "FUELSYSTEM TANK TOTAL QUANTITY", "Gallons" },
        { "FUELSYSTEM TANK WEIGHT", "Pounds" },
        { "FUELSYSTEM TRIGGER STATUS", "" },
        { "FUELSYSTEM VALVE OPEN", "" },
        { "FUELSYSTEM VALVE SWITCH", "" },
        { "FUELTRUCK HOSE DEPLOYED", "Percent over 100" },
        { "FUELTRUCK HOSE END POSX", "Meters" },
        { "FUELTRUCK HOSE END POSZ", "Meters" },
        { "FUELTRUCK HOSE END RELATIVE HEADING", "Degrees" },
        { "FUEL CROSS FEED", "Enum" },
        { "FUEL DUMP ACTIVE", "" },
        { "FUEL DUMP SWITCH", "Bool" },
        { "FUEL LEFT CAPACITY", "Gallons" },
        { "FUEL LEFT QUANTITY", "Gallons" },
        { "FUEL PUMP", "" },
        { "FUEL RIGHT CAPACITY", "Gallons" },
        { "FUEL RIGHT QUANTITY", "Gallons" },
        { "FUEL SELECTED QUANTITY", "Gallons" },
        { "FUEL SELECTED QUANTITY PERCENT", "Percent Over 100" },
        { "FUEL SELECTED TRANSFER MODE", "Enum" },
        { "FUEL TANK CENTER2 CAPACITY", "Gallons" },
        { "FUEL TANK CENTER2 LEVEL", "Percent Over 100" },
        { "FUEL TANK CENTER2 QUANTITY", "Gallons" },
        { "FUEL TANK CENTER3 CAPACITY", "Gallons" },
        { "FUEL TANK CENTER3 LEVEL", "Percent Over 100" },
        { "FUEL TANK CENTER3 QUANTITY", "Gallons" },
        { "FUEL TANK CENTER CAPACITY", "Gallons" },
        { "FUEL TANK CENTER LEVEL", "Percent Over 100" },
        { "FUEL TANK CENTER QUANTITY", "Gallons" },
        { "FUEL TANK EXTERNAL1 CAPACITY", "Gallons" },
        { "FUEL TANK EXTERNAL1 LEVEL", "Percent Over 100" },
        { "FUEL TANK EXTERNAL1 QUANTITY", "Gallons" },
        { "FUEL TANK EXTERNAL2 CAPACITY", "Gallons" },
        { "FUEL TANK EXTERNAL2 LEVEL", "Percent Over 100" },
        { "FUEL TANK EXTERNAL2 QUANTITY", "Gallons" },
        { "FUEL TANK LEFT AUX CAPACITY", "Gallons" },
        { "FUEL TANK LEFT AUX LEVEL", "Percent Over 100" },
        { "FUEL TANK LEFT AUX QUANTITY", "Gallons" },
        { "FUEL TANK LEFT MAIN CAPACITY", "Gallons" },
        { "FUEL TANK LEFT MAIN LEVEL", "Percent Over 100" },
        { "FUEL TANK LEFT MAIN QUANTITY", "Gallons" },
        { "FUEL TANK LEFT TIP CAPACITY", "Gallons" },
        { "FUEL TANK LEFT TIP LEVEL", "Percent Over 100" },
        { "FUEL TANK LEFT TIP QUANTITY", "Gallons" },
        { "FUEL TANK RIGHT AUX CAPACITY", "Gallons" },
        { "FUEL TANK RIGHT AUX LEVEL", "Percent Over 100" },
        { "FUEL TANK RIGHT AUX QUANTITY", "Gallons" },
        { "FUEL TANK RIGHT MAIN CAPACITY", "Gallons" },
        { "FUEL TANK RIGHT MAIN LEVEL", "Percent Over 100" },
        { "FUEL TANK RIGHT MAIN QUANTITY", "Gallons" },
        { "FUEL TANK RIGHT TIP CAPACITY", "Gallons" },
        { "FUEL TANK RIGHT TIP LEVEL", "Percent Over 100" },
        { "FUEL TANK RIGHT TIP QUANTITY", "Gallons" },
        { "FUEL TANK SELECTOR", "Enum" },
        { "FUEL TOTAL CAPACITY", "Gallons" },
        { "FUEL TOTAL QUANTITY", "Gallons" },
        { "FUEL TOTAL QUANTITY WEIGHT", "Pounds" },
        { "FUEL TRANSFER PUMP ON", "" },
        { "FUEL WEIGHT PER GALLON", "Pounds" },
        { "FULL THROTTLE THRUST TO WEIGHT RATIO", "Number" },
        { "GAMEPLAY CAMERA FOCUS", "" },
        { "GEAR ANIMATION POSITION", "Number" },
        { "GEAR AUX POSITION", "Percent Over 100" },
        { "GEAR AUX STEER ANGLE", "Radians" },
        { "GEAR AUX STEER ANGLE PCT", "Percent Over 100" },
        { "GEAR CENTER POSITION", "Percent Over 100" },
        { "GEAR CENTER STEER ANGLE", "Radians" },
        { "GEAR CENTER STEER ANGLE PCT", "Percent Over 100" },
        { "GEAR DAMAGE BY SPEED", "Bool" },
        { "GEAR EMERGENCY HANDLE POSITION", "Bool" },
        { "GEAR HANDLE POSITION", "Bool" },
        { "GEAR HYDRAULIC PRESSURE", "Pound force per square foot (psf)" },
        { "GEAR IS ON GROUND", "bool" },
        { "GEAR IS SKIDDING", "bool" },
        { "GEAR LEFT POSITION", "Percent Over 100" },
        { "GEAR LEFT STEER ANGLE", "Radians" },
        { "GEAR LEFT STEER ANGLE PCT", "Percent Over 100" },
        { "GEAR POSITION", "Enum" },
        { "GEAR RIGHT POSITION", "Percent Over 100" },
        { "GEAR RIGHT STEER ANGLE", "Radians" },
        { "GEAR RIGHT STEER ANGLE PCT", "Percent Over 100" },
        { "GEAR SKIDDING FACTOR", "Percent Over 100" },
        { "GEAR SPEED EXCEEDED", "Bool" },
        { "GEAR STEER ANGLE", "Radians" },
        { "GEAR STEER ANGLE PCT", "Percent Over 100" },
        { "GEAR TAIL POSITION", "Percent Over 100" },
        { "GEAR TOTAL PCT EXTENDED", "Percentage" },
        { "GEAR WARNING", "Enum" },
        { "GEAR WATER DEPTH", "Feet" },
        { "GENERAL ENG ANTI ICE POSITION", "Bool" },
        { "GENERAL ENG COMBUSTION", "Bool" },
        { "GENERAL ENG COMBUSTION EX1", "" },
        { "GENERAL ENG COMBUSTION SOUND PERCENT", "Percent" },
        { "GENERAL ENG DAMAGE PERCENT", "Percent" },
        { "GENERAL ENG ELAPSED TIME", "Hours" },
        { "GENERAL ENG EXHAUST GAS TEMPERATURE", "Rankine" },
        { "GENERAL ENG FAILED", "Bool" },
        { "GENERAL ENG FIRE DETECTED", "" },
        { "GENERAL ENG FUEL PRESSURE", "Psi" },
        { "GENERAL ENG FUEL PUMP ON", "Bool" },
        { "GENERAL ENG FUEL PUMP SWITCH", "Bool" },
        { "GENERAL ENG FUEL PUMP SWITCH EX1", "" },
        { "GENERAL ENG FUEL USED SINCE START", "Pounds" },
        { "GENERAL ENG FUEL VALVE", "Bool" },
        { "GENERAL ENG GENERATOR ACTIVE", "Bool" },
        { "GENERAL ENG GENERATOR SWITCH", "Bool" },
        { "GENERAL ENG HOBBS ELAPSED TIME", "" },
        { "GENERAL ENG MASTER ALTERNATOR", "Bool" },
        { "GENERAL ENG MAX REACHED RPM", "Rpm" },
        { "GENERAL ENG MIXTURE LEVER POSITION", "Percent" },
        { "GENERAL ENG OIL LEAKED PERCENT", "Percent" },
        { "GENERAL ENG OIL PRESSURE", "Psf" },
        { "GENERAL ENG OIL TEMPERATURE", "Rankine" },
        { "GENERAL ENG PCT MAX RPM", "Percent" },
        { "GENERAL ENG PROPELLER LEVER POSITION", "Percent" },
        { "GENERAL ENG REVERSE THRUST ENGAGED", "Bool" },
        { "GENERAL ENG RPM", "Rpm" },
        { "GENERAL ENG STARTER", "Bool" },
        { "GENERAL ENG STARTER ACTIVE", "Bool" },
        { "GENERAL ENG THROTTLE LEVER POSITION", "Percent" },
        { "GENERAL ENG THROTTLE MANAGED MODE", "Number" },
        { "GLASSCOCKPIT AUTOMATIC BRIGHTNESS", "Percent Over 100" },
        { "GPS APPROACH AIRPORT ID", "String" },
        { "GPS APPROACH APPROACH ID", "String" },
        { "GPS APPROACH APPROACH INDEX", "Number" },
        { "GPS APPROACH APPROACH TYPE", "Enum" },
        { "GPS APPROACH IS FINAL", "Bool" },
        { "GPS APPROACH IS MISSED", "Bool" },
        { "GPS APPROACH IS WP RUNWAY", "Bool" },
        { "GPS APPROACH MODE", "Enum" },
        { "GPS APPROACH SEGMENT TYPE", "Enum" },
        { "GPS APPROACH TIMEZONE DEVIATION", "Seconds" },
        { "GPS APPROACH TRANSITION ID", "String" },
        { "GPS APPROACH TRANSITION INDEX", "Number" },
        { "GPS APPROACH WP COUNT", "Number" },
        { "GPS APPROACH WP INDEX", "Number" },
        { "GPS APPROACH WP TYPE", "Enum" },
        { "GPS CDI SCALING", "Meters" },
        { "GPS COURSE TO STEER", "Radians" },
        { "GPS DRIVES NAV1", "Bool" },
        { "GPS ETA", "Seconds" },
        { "GPS ETE", "Seconds" },
        { "GPS FLIGHTPLAN TOTAL DISTANCE", "" },
        { "GPS FLIGHT PLAN WP COUNT", "Number" },
        { "GPS FLIGHT PLAN WP INDEX", "Number" },
        { "GPS GROUND MAGNETIC TRACK", "Radians" },
        { "GPS GROUND SPEED", "Meters per second" },
        { "GPS GROUND TRUE HEADING", "Radians" },
        { "GPS GROUND TRUE TRACK", "Radians" },
        { "GPS GSI SCALING", "Meters" },
        { "GPS HAS GLIDEPATH", "Meters" },
        { "GPS IS ACTIVE FLIGHT PLAN", "Bool" },
        { "GPS IS ACTIVE WAY POINT", "Bool" },
        { "GPS IS ACTIVE WP LOCKED", "Bool" },
        { "GPS IS APPROACH ACTIVE", "Bool" },
        { "GPS IS APPROACH LOADED", "Bool" },
        { "GPS IS ARRIVED", "Bool" },
        { "GPS IS DIRECTTO FLIGHTPLAN", "Bool" },
        { "GPS MAGVAR", "Radians" },
        { "GPS OBS ACTIVE", "" },
        { "GPS OBS VALUE", "" },
        { "GPS OVERRIDDEN", "Bool" },
        { "GPS POSITION ALT", "Meters" },
        { "GPS POSITION LAT", "Degrees" },
        { "GPS POSITION LON", "Degrees" },
        { "GPS TARGET ALTITUDE", "Meters" },
        { "GPS TARGET DISTANCE", "Meters" },
        { "GPS VERTICAL ANGLE", "Degrees" },
        { "GPS VERTICAL ANGLE ERROR", "Degrees" },
        { "GPS VERTICAL ERROR", "Meters" },
        { "GPS WP BEARING", "Radians" },
        { "GPS WP CROSS TRK", "Meters" },
        { "GPS WP DESIRED TRACK", "Radians" },
        { "GPS WP DISTANCE", "Meters" },
        { "GPS WP ETA", "Seconds" },
        { "GPS WP ETE", "Seconds" },
        { "GPS WP NEXT ALT", "Meters" },
        { "GPS WP NEXT ID", "String" },
        { "GPS WP NEXT LAT", "Degrees" },
        { "GPS WP NEXT LON", "Degrees" },
        { "GPS WP PREV ALT", "Meters" },
        { "GPS WP PREV ID", "String" },
        { "GPS WP PREV LAT", "Degrees" },
        { "GPS WP PREV LON", "Degrees" },
        { "GPS WP PREV VALID", "Bool" },
        { "GPS WP TRACK ANGLE ERROR", "Radians" },
        { "GPS WP TRUE BEARING", "Radians" },
        { "GPS WP TRUE REQ HDG", "Radians" },
        { "GPS WP VERTICAL SPEED", "Meters per second" },
        { "GPWS SYSTEM ACTIVE", "Bool" },
        { "GPWS WARNING", "Bool" },
        { "GROUNDPOWERUNIT HOSE DEPLOYED", "Percent over 100" },
        { "GROUNDPOWERUNIT HOSE END POSX", "Meters" },
        { "GROUNDPOWERUNIT HOSE END POSZ", "Meters" },
        { "GROUNDPOWERUNIT HOSE END RELATIVE HEADING", "Degrees" },
        { "GROUND ALTITUDE", "Meters" },
        { "GROUND VELOCITY", "Knots" },
        { "GUN AMMO", "" },
        { "GYRO DRIFT ERROR", "Radians" },
        { "G FORCE", "GForce" },
        { "G LIMITER SETTING", "Enum" },
        { "HAND ANIM STATE", "Enum" },
        { "HAS STALL PROTECTION", "Bool" },
        { "HEADING INDICATOR", "Radians" },
        { "HOLDBACK BAR INSTALLED", "Bool" },
        { "HSI BEARING", "Degrees" },
        { "HSI BEARING VALID", "Bool" },
        { "HSI CDI NEEDLE", "Number" },
        { "HSI CDI NEEDLE VALID", "Bool" },
        { "HSI DISTANCE", "Nautical miles" },
        { "HSI GSI NEEDLE", "Number" },
        { "HSI GSI NEEDLE VALID", "Bool" },
        { "HSI HAS LOCALIZER", "Bool" },
        { "HSI SPEED", "Knots" },
        { "HSI STATION IDENT", "String(6)" },
        { "HSI TF FLAGS", "Enum" },
        { "HYDRAULIC PRESSURE", "Pound force per square foot" },
        { "HYDRAULIC RESERVOIR PERCENT", "Percent Over 100" },
        { "HYDRAULIC SWITCH", "Bool" },
        { "HYDRAULIC SYSTEM INTEGRITY", "Percent Over 100" },
        { "IDLE ANIMATION ID", "" },
        { "INCIDENCE ALPHA", "Radians" },
        { "INCIDENCE BETA", "Radians" },
        { "INDICATED ALTITUDE", "Feet" },
        { "INDICATED ALTITUDE CALIBRATED", "Feet" },
        { "INDICATED ALTITUDE EX1", "Feet" },
        { "INDUCTOR COMPASS HEADING REF", "Radians" },
        { "INDUCTOR COMPASS PERCENT DEVIATION", "Percent over 100" },
        { "INNER MARKER", "Bool" },
        { "INNER MARKER LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "INSTRUMENTS AVAILABLE", "" },
        { "INTERACTIVE POINT BANK", "Degrees" },
        { "INTERACTIVE POINT GOAL", "Percent over 100" },
        { "INTERACTIVE POINT HEADING", "Degrees" },
        { "INTERACTIVE POINT JETWAY LEFT BEND", "Percent" },
        { "INTERACTIVE POINT JETWAY LEFT DEPLOYMENT", "Degrees" },
        { "INTERACTIVE POINT JETWAY RIGHT BEND", "Percent" },
        { "INTERACTIVE POINT JETWAY RIGHT DEPLOYMENT", "Degrees" },
        { "INTERACTIVE POINT JETWAY TOP HORIZONTAL", "Percent" },
        { "INTERACTIVE POINT JETWAY TOP VERTICAL", "Percent" },
        { "INTERACTIVE POINT OPEN", "Percent over 100" },
        { "INTERACTIVE POINT PITCH", "Degrees" },
        { "INTERACTIVE POINT POSX", "Feet" },
        { "INTERACTIVE POINT POSY", "Feet" },
        { "INTERACTIVE POINT POSZ", "Feet" },
        { "INTERACTIVE POINT TYPE", "Enum" },
        { "INTERCOM MODE", "Enum" },
        { "INTERCOM SYSTEM ACTIVE", "Bool" },
        { "IS ALTITUDE FREEZE ON", "Bool" },
        { "IS ANY INTERIOR LIGHT ON", "" },
        { "IS ATTACHED TO SLING", "Bool" },
        { "IS ATTITUDE FREEZE ON", "Bool" },
        { "IS GEAR FLOATS", "Bool" },
        { "IS GEAR RETRACTABLE", "Bool" },
        { "IS GEAR SKIDS", "Bool" },
        { "IS GEAR SKIS", "Bool" },
        { "IS GEAR WHEELS", "Bool" },
        { "IS LATITUDE LONGITUDE FREEZE ON", "Bool" },
        { "IS SLEW ACTIVE", "Bool" },
        { "IS SLEW ALLOWED", "Bool" },
        { "IS TAIL DRAGGER", "Bool" },
        { "IS USER SIM", "Bool" },
        { "JETWAY HOOD LEFT BEND", "Percent" },
        { "JETWAY HOOD LEFT DEPLOYMENT", "Degrees" },
        { "JETWAY HOOD RIGHT BEND", "Percent" },
        { "JETWAY HOOD RIGHT DEPLOYMENT", "Degrees" },
        { "JETWAY HOOD TOP HORIZONTAL", "Percent" },
        { "JETWAY HOOD TOP VERTICAL", "Percent" },
        { "JETWAY MOVING", "Boolean" },
        { "JETWAY WHEEL ORIENTATION CURRENT", "Degrees" },
        { "JETWAY WHEEL ORIENTATION TARGET", "Degrees" },
        { "JETWAY WHEEL SPEED", "Meters per second" },
        { "KOHLSMAN SETTING HG", "Inches of Mercury, inHg" },
        { "KOHLSMAN SETTING MB", "Millibars" },
        { "KOHLSMAN SETTING STD", "Bool" },
        { "LANDING LIGHT PBH", "`SIMCONNECT_DATA_XYZ` structure" },
        { "LAUNCHBAR HELD EXTENDED", "Bool" },
        { "LAUNCHBAR POSITION", "Percent_over_100" },
        { "LAUNCHBAR SWITCH", "Bool" },
        { "LEADING EDGE FLAPS LEFT ANGLE", "Radians" },
        { "LEADING EDGE FLAPS LEFT INDEX", "Number" },
        { "LEADING EDGE FLAPS LEFT PERCENT", "Percent Over 100" },
        { "LEADING EDGE FLAPS RIGHT ANGLE", "Radians" },
        { "LEADING EDGE FLAPS RIGHT INDEX", "Number" },
        { "LEADING EDGE FLAPS RIGHT PERCENT", "Percent Over 100" },
        { "LEFT WHEEL ROTATION ANGLE", "Radians" },
        { "LEFT WHEEL RPM", "Rpm" },
        { "LIGHT BACKLIGHT INTENSITY", "Percent over 100" },
        { "LIGHT BEACON", "Bool" },
        { "LIGHT BEACON ON", "Bool" },
        { "LIGHT BRAKE ON", "Bool" },
        { "LIGHT CABIN", "Bool" },
        { "LIGHT CABIN ON", "Bool" },
        { "LIGHT CABIN POWER SETTING", "" },
        { "LIGHT GLARESHIELD", "" },
        { "LIGHT GLARESHIELD ON", "" },
        { "LIGHT GLARESHIELD POWER SETTING", "" },
        { "LIGHT GYROLIGHT INTENSITY", "Percent over 100" },
        { "LIGHT HEADLIGHT INTENSITY", "Percent over 100" },
        { "LIGHT HEAD ON", "Bool" },
        { "LIGHT LANDING", "Bool" },
        { "LIGHT LANDING ON", "Bool" },
        { "LIGHT LOGO", "Bool" },
        { "LIGHT LOGO ON", "Bool" },
        { "LIGHT NAV", "Bool" },
        { "LIGHT NAV ON", "Bool" },
        { "LIGHT ON STATES", "Mask" },
        { "LIGHT PANEL", "Bool" },
        { "LIGHT PANEL ON", "Bool" },
        { "LIGHT PANEL POWER SETTING", "" },
        { "LIGHT PEDESTRAL", "" },
        { "LIGHT PEDESTRAL ON", "" },
        { "LIGHT PEDESTRAL POWER SETTING", "" },
        { "LIGHT POTENTIOMETER", "" },
        { "LIGHT RECOGNITION", "Bool" },
        { "LIGHT RECOGNITION ON", "Bool" },
        { "LIGHT STATES", "Mask" },
        { "LIGHT STROBE", "Bool" },
        { "LIGHT STROBE ON", "Bool" },
        { "LIGHT TAXI", "Bool" },
        { "LIGHT TAXI ON", "Bool" },
        { "LIGHT WING", "Bool" },
        { "LIGHT WING ON", "Bool" },
        { "LINEAR CL ALPHA", "Per radian" },
        { "MACH MAX OPERATE", "Mach" },
        { "MAGNETIC COMPASS", "Degrees" },
        { "MAGVAR", "Degrees" },
        { "MANUAL FUEL PUMP HANDLE", "Percent over 100" },
        { "MANUAL INSTRUMENT LIGHTS", "Bool" },
        { "MARKER AVAILABLE", "Bool" },
        { "MARKER BEACON SENSITIVITY HIGH", "Bool" },
        { "MARKER BEACON STATE", "Enum" },
        { "MARKER BEACON TEST MUTE", "Bool" },
        { "MARKER SOUND", "Bool" },
        { "MARSHALLER AIRCRAFT DIRECTION PARKINGSPACE", "" },
        { "MARSHALLER AIRCRAFT DISTANCE", "" },
        { "MARSHALLER AIRCRAFT DISTANCE DIRECTION X PARKINGSPACE", "" },
        { "MARSHALLER AIRCRAFT DISTANCE DIRECTION Z PARKINGSPACE", "" },
        { "MARSHALLER AIRCRAFT ENGINE SHUTDOWN", "" },
        { "MARSHALLER AIRCRAFT HEADING PARKINGSPACE", "" },
        { "MARSHALLER AIRCRAFT PROJECTION POINT PARKINGSPACE", "" },
        { "MARSHALLER AIRCRAFT VELOCITY", "" },
        { "MASTER CAUTION ACKNOWLEDGED", "Bool" },
        { "MASTER CAUTION ACTIVE", "Bool" },
        { "MASTER IGNITION SWITCH", "Bool" },
        { "MASTER WARNING ACKNOWLEDGED", "Bool" },
        { "MASTER WARNING ACTIVE", "Bool" },
        { "MAX GROSS WEIGHT", "Pounds" },
        { "MAX G FORCE", "Gforce" },
        { "MAX RATED ENGINE RPM", "Rpm" },
        { "MIDDLE MARKER", "Bool" },
        { "MIDDLE MARKER LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "MIN DRAG VELOCITY", "Feet per second" },
        { "MIN G FORCE", "Gforce" },
        { "MISSION SCORE", "" },
        { "NAV ACTIVE FREQUENCY", "MHz" },
        { "NAV AVAILABLE", "Bool" },
        { "NAV BACK COURSE FLAGS", "Flags" },
        { "NAV CDI", "Number" },
        { "NAV CLOSE DME", "Nautical miles" },
        { "NAV CLOSE FREQUENCY", "Hz" },
        { "NAV CLOSE IDENT", "String" },
        { "NAV CLOSE LOCALIZER", "Degrees" },
        { "NAV CLOSE NAME", "String" },
        { "NAV CODES", "Flags" },
        { "NAV DME", "Nautical miles" },
        { "NAV DMESPEED", "Knots" },
        { "NAV DME LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "NAV FREQUENCY", "Hz" },
        { "NAV GLIDE SLOPE", "Number" },
        { "NAV GLIDE SLOPE ERROR", "Degrees" },
        { "NAV GLIDE SLOPE LENGTH", "" },
        { "NAV GSI", "Number" },
        { "NAV GS FLAG", "Bool" },
        { "NAV GS LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "NAV GS LLAF64", "LLA structure" },
        { "NAV HAS CLOSE DME", "Bool" },
        { "NAV HAS CLOSE LOCALIZER", "Bool" },
        { "NAV HAS DME", "Bool" },
        { "NAV HAS GLIDE SLOPE", "Bool" },
        { "NAV HAS LOCALIZER", "Bool" },
        { "NAV HAS NAV", "Bool" },
        { "NAV HAS TACAN", "Bool" },
        { "NAV IDENT", "String" },
        { "NAV LOCALIZER", "Degrees" },
        { "NAV LOC AIRPORT IDENT", "String" },
        { "NAV LOC RUNWAY DESIGNATOR", "String" },
        { "NAV LOC RUNWAY NUMBER", "Enum" },
        { "NAV MAGVAR", "Degrees" },
        { "NAV NAME", "String" },
        { "NAV OBS", "Degrees" },
        { "NAV RADIAL", "Degrees" },
        { "NAV RADIAL ERROR", "Degrees" },
        { "NAV RAW GLIDE SLOPE", "Degrees" },
        { "NAV RELATIVE BEARING TO STATION", "Degrees" },
        { "NAV SIGNAL", "Number" },
        { "NAV SOUND", "Bool" },
        { "NAV STANDBY FREQUENCY", "MHz" },
        { "NAV TOFROM", "Enum" },
        { "NAV VOLUME", "" },
        { "NAV VOR DISTANCE", "Meters" },
        { "NAV VOR LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "NAV VOR LLAF64", "LLA structure" },
        { "NEW ELECTRICAL SYSTEM", "Bool" },
        { "NEW FUEL SYSTEM", "Bool" },
        { "NOSEWHEEL LOCK ON", "Bool" },
        { "NOSEWHEEL MAX STEERING ANGLE", "Radians" },
        { "NUMBER OF CATAPULTS", "Number" },
        { "NUMBER OF ENGINES", "Number" },
        { "NUM FUEL SELECTORS", "Number" },
        { "NUM SLING CABLES", "Number" },
        { "OIL AMOUNT", "" },
        { "OIL COOLING FLAPS POSITION", "Percent over 100" },
        { "OLD ENG STARTER", "" },
        { "ON ANY RUNWAY", "Bool" },
        { "OUTER MARKER", "Bool" },
        { "OUTER MARKER LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "OVERSPEED WARNING", "Bool" },
        { "PANEL ANTI ICE SWITCH", "Bool" },
        { "PANEL AUTO FEATHER SWITCH", "Bool" },
        { "PARTIAL PANEL ADF", "Enum" },
        { "PARTIAL PANEL AIRSPEED", "Enum" },
        { "PARTIAL PANEL ALTIMETER", "Enum" },
        { "PARTIAL PANEL ATTITUDE", "Enum" },
        { "PARTIAL PANEL AVIONICS", "Enum" },
        { "PARTIAL PANEL COMM", "Enum" },
        { "PARTIAL PANEL COMPASS", "Enum" },
        { "PARTIAL PANEL ELECTRICAL", "Enum" },
        { "PARTIAL PANEL ENGINE", "Enum" },
        { "PARTIAL PANEL FUEL INDICATOR", "Enum" },
        { "PARTIAL PANEL HEADING", "Enum" },
        { "PARTIAL PANEL NAV", "Enum" },
        { "PARTIAL PANEL PITOT", "Enum" },
        { "PARTIAL PANEL TRANSPONDER", "Enum" },
        { "PARTIAL PANEL TURN COORDINATOR", "Enum" },
        { "PARTIAL PANEL VACUUM", "Enum" },
        { "PARTIAL PANEL VERTICAL VELOCITY", "Enum" },
        { "PAYLOAD STATION COUNT", "Number" },
        { "PAYLOAD STATION NAME", "String" },
        { "PAYLOAD STATION NUM SIMOBJECTS", "Number" },
        { "PAYLOAD STATION OBJECT", "String" },
        { "PAYLOAD STATION WEIGHT", "Pounds" },
        { "PILOT TRANSMITTER TYPE", "Enum" },
        { "PILOT TRANSMITTING", "Bool" },
        { "PITOT HEAT", "Bool" },
        { "PITOT HEAT SWITCH", "Enum" },
        { "PITOT ICE PCT", "Percent over 100" },
        { "PLANE ALTITUDE", "Feet" },
        { "PLANE ALT ABOVE GROUND", "Feet" },
        { "PLANE ALT ABOVE GROUND MINUS CG", "Feet" },
        { "PLANE BANK DEGREES", "Radians" },
        { "PLANE HEADING DEGREES GYRO", "Radians" },
        { "PLANE HEADING DEGREES MAGNETIC", "Radians" },
        { "PLANE HEADING DEGREES TRUE", "Radians" },
        { "PLANE IN PARKING STATE", "" },
        { "PLANE LATITUDE", "Radians" },
        { "PLANE LONGITUDE", "Radians" },
        { "PLANE PITCH DEGREES", "Radians" },
        { "PLANE TOUCHDOWN BANK DEGREES", "Degrees" },
        { "PLANE TOUCHDOWN HEADING DEGREES MAGNETIC", "Degrees" },
        { "PLANE TOUCHDOWN HEADING DEGREES TRUE", "Degrees" },
        { "PLANE TOUCHDOWN LATITUDE", "Radians" },
        { "PLANE TOUCHDOWN LONGITUDE", "Radians" },
        { "PLANE TOUCHDOWN NORMAL VELOCITY", "Feet per second" },
        { "PLANE TOUCHDOWN PITCH DEGREES", "Degrees" },
        { "PRESSURE ALTITUDE", "Meters" },
        { "PRESSURIZATION CABIN ALTITUDE", "Feet" },
        { "PRESSURIZATION CABIN ALTITUDE GOAL", "Feet" },
        { "PRESSURIZATION CABIN ALTITUDE RATE", "Feet per second" },
        { "PRESSURIZATION DUMP SWITCH", "Bool" },
        { "PRESSURIZATION PRESSURE DIFFERENTIAL", "Pounds per square foot" },
        { "PROPELLER ADVANCED SELECTION", "" },
        { "PROP AUTO CRUISE ACTIVE", "Bool" },
        { "PROP AUTO FEATHER ARMED", "Bool" },
        { "PROP BETA", "Radians" },
        { "PROP BETA MAX", "Radians" },
        { "PROP BETA MIN", "Radians" },
        { "PROP BETA MIN REVERSE", "Radians" },
        { "PROP DEICE SWITCH", "Bool" },
        { "PROP FEATHERED", "Bool" },
        { "PROP FEATHERING INHIBIT", "Bool" },
        { "PROP FEATHER SWITCH", "Bool" },
        { "PROP MAX RPM PERCENT", "Percent" },
        { "PROP ROTATION ANGLE", "Radians" },
        { "PROP RPM", "Rpm" },
        { "PROP SYNC ACTIVE", "Bool" },
        { "PROP SYNC DELTA LEVER", "Position" },
        { "PROP THRUST", "Pounds" },
        { "PROP TYPE AVAILABLE", "" },
        { "PUSHBACK ANGLE", "Radians" },
        { "PUSHBACK ATTACHED", "Boolean" },
        { "PUSHBACK AVAILABLE", "" },
        { "PUSHBACK CONTACTX", "Feet" },
        { "PUSHBACK CONTACTY", "Feet" },
        { "PUSHBACK CONTACTZ", "Feet" },
        { "PUSHBACK STATE", "Enum" },
        { "PUSHBACK WAIT", "Bool" },
        { "RACE LAST LAP TIME", "" },
        { "RADIATOR COOLING FLAPS POSITION", "Percent over 100" },
        { "RADIOS AVAILABLE", "" },
        { "RADIO HEIGHT", "Feet" },
        { "RAD INS SWITCH", "Bool" },
        { "REALISM", "Number" },
        { "REALISM CRASH DETECTION", "Bool" },
        { "REALISM CRASH WITH OTHERS", "Bool" },
        { "RECIP CARBURETOR TEMPERATURE", "Celsius" },
        { "RECIP ENG ALTERNATE AIR POSITION", "Position" },
        { "RECIP ENG ANTIDETONATION FLOW RATE", "Gallons per hour" },
        { "RECIP ENG ANTIDETONATION TANK MAX QUANTITY", "Gallons" },
        { "RECIP ENG ANTIDETONATION TANK QUANTITY", "Gallons" },
        { "RECIP ENG ANTIDETONATION TANK VALVE", "Bool" },
        { "RECIP ENG BRAKE POWER", "Foot pounds per second" },
        { "RECIP ENG COOLANT RESERVOIR PERCENT", "Percent" },
        { "RECIP ENG COWL FLAP POSITION", "Percent" },
        { "RECIP ENG CYLINDER HEAD TEMPERATURE", "Celsius" },
        { "RECIP ENG CYLINDER HEALTH", "Percent_over_100" },
        { "RECIP ENG DETONATING", "Bool" },
        { "RECIP ENG EMERGENCY BOOST ACTIVE", "Bool" },
        { "RECIP ENG EMERGENCY BOOST ELAPSED TIME", "Hours" },
        { "RECIP ENG ENGINE MASTER SWITCH", "" },
        { "RECIP ENG FUEL AVAILABLE", "Bool" },
        { "RECIP ENG FUEL FLOW", "Pounds per hour" },
        { "RECIP ENG FUEL NUMBER TANKS USED", "Number" },
        { "RECIP ENG FUEL TANKS USED", "Mask" },
        { "RECIP ENG FUEL TANK SELECTOR", "Enum" },
        { "RECIP ENG GLOW PLUG ACTIVE", "" },
        { "RECIP ENG LEFT MAGNETO", "Bool" },
        { "RECIP ENG MANIFOLD PRESSURE", "Psi" },
        { "RECIP ENG NITROUS TANK MAX QUANTITY", "Gallons" },
        { "RECIP ENG NITROUS TANK QUANTITY", "Gallons" },
        { "RECIP ENG NITROUS TANK VALVE", "Bool" },
        { "RECIP ENG NUM CYLINDERS", "Number" },
        { "RECIP ENG NUM CYLINDERS FAILED", "Number" },
        { "RECIP ENG PRIMER", "Bool" },
        { "RECIP ENG RADIATOR TEMPERATURE", "Celsius" },
        { "RECIP ENG RIGHT MAGNETO", "Bool" },
        { "RECIP ENG STARTER TORQUE", "Foot pound" },
        { "RECIP ENG SUPERCHARGER ACTIVE GEAR", "Number" },
        { "RECIP ENG TURBINE INLET TEMPERATURE", "Celsius" },
        { "RECIP ENG TURBOCHARGER FAILED", "Bool" },
        { "RECIP ENG WASTEGATE POSITION", "Percent" },
        { "RECIP MIXTURE RATIO", "Ratio" },
        { "REJECTED TAKEOFF BRAKES ACTIVE", "Bool" },
        { "RELATIVE WIND VELOCITY BODY X", "Feet per second" },
        { "RELATIVE WIND VELOCITY BODY Y", "Feet per second" },
        { "RELATIVE WIND VELOCITY BODY Z", "Feet per second" },
        { "RENORACE CATEGORY", "Number" },
        { "RETRACT FLOAT SWITCH", "Bool" },
        { "RETRACT LEFT FLOAT EXTENDED", "Percent (0 is fully retracted, 100 is fully extended)" },
        { "RETRACT RIGHT FLOAT EXTENDED", "Percent (0 is fully retracted, 100 is fully extended)" },
        { "RIGHT WHEEL ROTATION ANGLE", "Radians" },
        { "RIGHT WHEEL RPM", "Rpm" },
        { "ROCKET AMMO", "" },
        { "ROTATION ACCELERATION BODY X", "Radians per second squared" },
        { "ROTATION ACCELERATION BODY Y", "Radians per second squared" },
        { "ROTATION ACCELERATION BODY Z", "Radians per second squared" },
        { "ROTATION VELOCITY BODY X", "Feet per second" },
        { "ROTATION VELOCITY BODY Y", "Feet per second" },
        { "ROTATION VELOCITY BODY Z", "Feet per second" },
        { "ROTOR BRAKE ACTIVE", "Bool" },
        { "ROTOR BRAKE HANDLE POS", "Percent Over 100" },
        { "ROTOR CHIP DETECTED", "Bool" },
        { "ROTOR CLUTCH ACTIVE", "Bool" },
        { "ROTOR CLUTCH SWITCH POS", "Bool" },
        { "ROTOR GOV ACTIVE", "Bool" },
        { "ROTOR GOV SWITCH POS", "Bool" },
        { "ROTOR LATERAL TRIM PCT", "Percent Over 100" },
        { "ROTOR ROTATION ANGLE", "Radians" },
        { "ROTOR RPM PCT", "Percent Over 100" },
        { "ROTOR TEMPERATURE", "Rankine" },
        { "RUDDER DEFLECTION", "Radians" },
        { "RUDDER DEFLECTION PCT", "Percent Over 100" },
        { "RUDDER PEDAL INDICATOR", "Position" },
        { "RUDDER PEDAL POSITION", "Position (-16K to 0) -16K = left pedal pushed full in" },
        { "RUDDER POSITION", "Position (-16K to 0) -16K = full left" },
        { "RUDDER TRIM", "Radians" },
        { "RUDDER TRIM DISABLED", "Bool" },
        { "RUDDER TRIM PCT", "Float. Percent over 100" },
        { "SEA LEVEL AMBIENT TEMPERATURE", "Celsius" },
        { "SEA LEVEL PRESSURE", "Millibars" },
        { "SELECTED DME", "Number" },
        { "SEMIBODY LOADFACTOR X", "" },
        { "SEMIBODY LOADFACTOR Y", "Number" },
        { "SEMIBODY LOADFACTOR YDOT", "Per second" },
        { "SEMIBODY LOADFACTOR Z", "" },
        { "SHUTOFF VALVE PULLED", "" },
        { "SIGMA SQRT", "Number" },
        { "SIMULATED RADIUS", "Feet" },
        { "SIM DISABLED", "Bool" },
        { "SIM ON GROUND", "Bool" },
        { "SIM SHOULD SET ON GROUND", "" },
        { "SLING ACTIVE PAYLOAD STATION", "Number" },
        { "SLING CABLE BROKEN", "Bool" },
        { "SLING CABLE EXTENDED LENGTH", "Feet" },
        { "SLING HOIST PERCENT DEPLOYED", "Percent_over_100" },
        { "SLING HOIST SWITCH", "" },
        { "SLING HOOK IN PICKUP MODE", "Bool" },
        { "SLING OBJECT ATTACHED", "Bool/String" },
        { "SLOPE TO ATC RUNWAY", "Radians" },
        { "SMART CAMERA ACTIVE", "" },
        { "SMART CAMERA INFO", "" },
        { "SMART CAMERA LIST", "" },
        { "SMART CAMERA LIST DESCRIPTION", "" },
        { "SMOKESYSTEM AVAILABLE", "Bool" },
        { "SMOKE ENABLE", "Bool" },
        { "SPEAKER ACTIVE", "Bool" },
        { "SPOILERONS LEFT POSITION", "Percent Over 100" },
        { "SPOILERONS RIGHT POSITION", "Percent Over 100" },
        { "SPOILERS ARMED", "Bool" },
        { "SPOILERS HANDLE POSITION", "Percent Over 100 or Position (16K = down, 0 = up)" },
        { "SPOILERS LEFT POSITION", "Percent Over 100 or Position (0 = retracted, 16K fully extended)" },
        { "SPOILERS RIGHT POSITION", "Percent Over 100 or Position (0 = retracted, 16K fully extended)" },
        { "SPOILERS WITHOUT SPOILERONS LEFT POSITION", "Percent Over 100" },
        { "SPOILERS WITHOUT SPOILERONS RIGHT POSITION", "Percent Over 100" },
        { "SPOILER AVAILABLE", "Bool" },
        { "STALL ALPHA", "Radians" },
        { "STALL HORN AVAILABLE", "Bool" },
        { "STALL PROTECTION OFF LIMIT", "Radians" },
        { "STALL PROTECTION ON GOAL", "Radians" },
        { "STALL PROTECTION ON LIMIT", "Radians" },
        { "STALL WARNING", "Bool" },
        { "STANDARD ATM TEMPERATURE", "Rankine" },
        { "STATIC CG TO GROUND", "Feet" },
        { "STATIC PITCH", "Radians" },
        { "STEER INPUT CONTROL", "Percent over 100" },
        { "STROBES AVAILABLE", "Bool" },
        { "STROBE FLASH", "" },
        { "STRUCTURAL DEICE SWITCH", "Bool" },
        { "STRUCTURAL ICE PCT", "Percent over 100" },
        { "STRUCT AMBIENT WIND", "Feet_per_second" },
        { "STRUCT BODY ROTATION ACCELERATION", "" },
        { "STRUCT BODY ROTATION VELOCITY", "`SIMCONNECT_DATA_XYZ` structure, radians per second" },
        { "STRUCT BODY VELOCITY", "`SIMCONNECT_DATA_XYZ` structure, feet per second" },
        { "STRUCT DAMAGEVISIBLE", "" },
        { "STRUCT ENGINE POSITION", "`SIMCONNECT_DATA_XYZ` structure, feet." },
        { "STRUCT EYEPOINT DYNAMIC ANGLE", "`SIMCONNECT_DATA_XYZ` structure, radians" },
        { "STRUCT EYEPOINT DYNAMIC OFFSET", "`SIMCONNECT_DATA_XYZ` structure, feet" },
        { "STRUCT LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "STRUCT LATLONALTPBH", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "STRUCT PBH32", "" },
        { "STRUCT REALISM VARS", "" },
        { "STRUCT SURFACE RELATIVE VELOCITY", "`SIMCONNECT_DATA_XYZ` structure, feet per second" },
        { "STRUCT WORLDVELOCITY", "`SIMCONNECT_DATA_XYZ` structure, feet per second" },
        { "STRUCT WORLD ACCELERATION", "`SIMCONNECT_DATA_XYZ` structure, feet per second squared" },
        { "STRUCT WORLD ROTATION VELOCITY", "`SIMCONNECT_DATA_XYZ` structure, radians per second" },
        { "STRUC AIRSPEED HOLD PID CONSTS", "" },
        { "STRUC HEADING HOLD PID CONSTS", "" },
        { "SUCTION PRESSURE", "Inches of Mercury, inHg" },
        { "SURFACE CONDITION", "Enum" },
        { "SURFACE INFO VALID", "Bool" },
        { "SURFACE RELATIVE GROUND SPEED", "Feet_per_second" },
        { "SURFACE TYPE", "Enum" },
        { "SYSTEMS AVAILABLE", "" },
        { "TACAN ACTIVE CHANNEL", "Number" },
        { "TACAN ACTIVE MODE", "Bool" },
        { "TACAN AVAILABLE", "Bool" },
        { "TACAN DRIVES NAV1", "Bool" },
        { "TACAN OBS", "Degrees" },
        { "TACAN STANDBY CHANNEL", "Number" },
        { "TACAN STANDBY MODE", "Bool" },
        { "TACAN STATION CDI", "Number" },
        { "TACAN STATION DISTANCE", "Meters" },
        { "TACAN STATION IDENT", "String(6)" },
        { "TACAN STATION LATLONALT", "`SIMCONNECT_DATA_LATLONALT`structure" },
        { "TACAN STATION RADIAL", "UNITS_DEGREES_ANGL16" },
        { "TACAN STATION RADIAL ERROR", "Degrees" },
        { "TACAN STATION TOFROM", "Enum" },
        { "TACAN VOLUME", "Percent Over 100" },
        { "TAILHOOK HANDLE", "Bool" },
        { "TAILHOOK POSITION", "Percent Over 100" },
        { "TAILWHEEL LOCK ON", "Bool" },
        { "THROTTLE LOWER LIMIT", "Percent" },
        { "TITLE", "Variable length string" },
        { "TOE BRAKES AVAILABLE", "Bool" },
        { "TOTAL AIR TEMPERATURE", "Celsius" },
        { "TOTAL VELOCITY", "Feet per second" },
        { "TOTAL WEIGHT", "Pounds" },
        { "TOTAL WEIGHT CROSS COUPLED MOI", "Slugs per feet squared" },
        { "TOTAL WEIGHT PITCH MOI", "Slugs per feet squared" },
        { "TOTAL WEIGHT ROLL MOI", "Slugs per feet squared" },
        { "TOTAL WEIGHT YAW MOI", "Slugs per feet squared" },
        { "TOTAL WORLD VELOCITY", "Feet per second" },
        { "TOW CONNECTION", "Bool" },
        { "TOW RELEASE HANDLE", "Percent over 100" },
        { "TRACK IR ENABLE", "" },
        { "TRAILING EDGE FLAPS LEFT ANGLE", "Radians" },
        { "TRAILING EDGE FLAPS LEFT INDEX", "Number" },
        { "TRAILING EDGE FLAPS LEFT PERCENT", "Percent Over 100" },
        { "TRAILING EDGE FLAPS RIGHT ANGLE", "Radians" },
        { "TRAILING EDGE FLAPS RIGHT INDEX", "Number" },
        { "TRAILING EDGE FLAPS RIGHT PERCENT", "Percent Over 100" },
        { "TRANSPONDER AVAILABLE", "Bool" },
        { "TRANSPONDER CODE", "BCO16" },
        { "TRANSPONDER IDENT", "Bool" },
        { "TRANSPONDER STATE", "Enum" },
        { "TRUE AIRSPEED SELECTED", "Bool" },
        { "TURB ENG AFTERBURNER", "Bool" },
        { "TURB ENG AFTERBURNER PCT ACTIVE", "Percent_over_100" },
        { "TURB ENG AFTERBURNER STAGE ACTIVE", "Number" },
        { "TURB ENG BLEED AIR", "Psi" },
        { "TURB ENG COMMANDED N1", "Percent" },
        { "TURB ENG CONDITION LEVER POSITION", "Enum" },
        { "TURB ENG CORRECTED FF", "Pounds per hour" },
        { "TURB ENG CORRECTED N1", "Percent" },
        { "TURB ENG CORRECTED N2", "Percent" },
        { "TURB ENG FREE TURBINE TORQUE", "" },
        { "TURB ENG FUEL AVAILABLE", "Bool" },
        { "TURB ENG FUEL FLOW PPH", "Pounds per hour" },
        { "TURB ENG HIGH IDLE", "Percent" },
        { "TURB ENG IGNITION SWITCH", "Bool" },
        { "TURB ENG IGNITION SWITCH EX1", "" },
        { "TURB ENG INLET TEMPERATURE", "UNITS_RANKINE" },
        { "TURB ENG IS IGNITING", "" },
        { "TURB ENG ITT", "Rankine" },
        { "TURB ENG JET THRUST", "Pounds" },
        { "TURB ENG LOW IDLE", "Percent" },
        { "TURB ENG MASTER STARTER SWITCH", "Bool" },
        { "TURB ENG MAX TORQUE PERCENT", "Percent" },
        { "TURB ENG N1", "Percent" },
        { "TURB ENG N2", "Percent" },
        { "TURB ENG NUM TANKS USED", "Number" },
        { "TURB ENG PRESSURE RATIO", "Ratio" },
        { "TURB ENG PRIMARY NOZZLE PERCENT", "Percent over 100" },
        { "TURB ENG REVERSE NOZZLE PERCENT", "Percent" },
        { "TURB ENG TANKS USED", "Mask" },
        { "TURB ENG TANK SELECTOR", "Enum" },
        { "TURB ENG THROTTLE COMMANDED N1", "Percent" },
        { "TURB ENG VIBRATION", "Number" },
        { "TURN COORDINATOR BALL", "Position 128 (-127 to 127)" },
        { "TURN COORDINATOR BALL INV", "Position 128 (-127 to 127)" },
        { "TURN INDICATOR RATE", "Radians per second" },
        { "TURN INDICATOR SWITCH", "Bool" },
        { "TYPICAL DESCENT RATE", "Feet per minute" },
        { "UNLIMITED FUEL", "Bool" },
        { "UNUSABLE FUEL TOTAL QUANTITY", "" },
        { "USER INPUT ENABLED", "Bool" },
        { "VARIOMETER RATE", "Feet per second" },
        { "VARIOMETER SWITCH", "Bool" },
        { "VELOCITY BODY X", "Feet per second" },
        { "VELOCITY BODY Y", "Feet per second" },
        { "VELOCITY BODY Z", "Feet per second" },
        { "VELOCITY WORLD X", "Feet per second" },
        { "VELOCITY WORLD Y", "Feet per second" },
        { "VELOCITY WORLD Z", "Feet per second" },
        { "VERTICAL SPEED", "Feet per second" },
        { "VERTICAL SPEED POSITION PCT", "Percent Over 100" },
        { "VISUAL MODEL RADIUS", "Meters" },
        { "WAGON BACK LINK LENGTH", "Meters" },
        { "WAGON BACK LINK ORIENTATION", "Degrees" },
        { "WAGON BACK LINK START POSZ", "Meters" },
        { "WAGON FRONT LINK LENGTH", "Meters" },
        { "WAGON FRONT LINK ORIENTATION", "Degrees" },
        { "WAGON FRONT LINK START POSZ", "Meters" },
        { "WARNING FUEL", "" },
        { "WARNING FUEL LEFT", "" },
        { "WARNING FUEL RIGHT", "" },
        { "WARNING LOW HEIGHT", "" },
        { "WARNING OIL PRESSURE", "" },
        { "WARNING VACUUM", "" },
        { "WARNING VACUUM LEFT", "" },
        { "WARNING VACUUM RIGHT", "" },
        { "WARNING VOLTAGE", "" },
        { "WATER BALLAST TANK CAPACITY", "Pounds" },
        { "WATER BALLAST TANK NUMBER", "Number" },
        { "WATER BALLAST TANK QUANTITY", "Pounds" },
        { "WATER BALLAST VALVE", "Bool" },
        { "WATER LEFT RUDDER EXTENDED", "Percentage" },
        { "WATER LEFT RUDDER STEER ANGLE", "Radians" },
        { "WATER LEFT RUDDER STEER ANGLE PCT", "Percent Over 100" },
        { "WATER RIGHT RUDDER EXTENDED", "Percentage" },
        { "WATER RIGHT RUDDER STEER ANGLE", "Radians" },
        { "WATER RIGHT RUDDER STEER ANGLE PCT", "Percent Over 100" },
        { "WATER RUDDER HANDLE POSITION", "Percent Over 100" },
        { "WHEEL ROTATION ANGLE", "Radians" },
        { "WHEEL RPM", "Rpm" },
        { "WINDSHIELD DEICE SWITCH", "Bool" },
        { "WINDSHIELD RAIN EFFECT AVAILABLE", "Bool" },
        { "WINDSHIELD WIND VELOCITY", "Feet per second" },
        { "WING AREA", "Square feet" },
        { "WING FLEX PCT", "Percent over 100" },
        { "WING SPAN", "Feet" },
        { "WISKEY COMPASS INDICATION DEGREES", "Degrees" },
        { "YAW STRING ANGLE", "Radians" },
        { "YAW STRING PCT EXTENDED", "Percent over 100" },
        { "YOKE X INDICATOR", "Position" },
        { "YOKE X INIDICATOR", "" },
        { "YOKE X POSITION", "Position (-16K to 0) -16K =" },
        { "YOKE X POSITION LINEAR", "Position (-16K to 0) -16K =" },
        { "YOKE X POSITION WITH AP", "Position (-16K to 0) -16K =" },
        { "YOKE X POSITION WITH AP LINEAR", "Position (-16K to 0) -16K =" },
        { "YOKE Y INDICATOR", "Position" },
        { "YOKE Y POSITION", "Position (-16K to 0) -16K = Yoke fully pushed in" },
        { "YOKE Y POSITION WITH AP", "Position (-16K to 0) -16K = Yoke fully pushed in" },
        { "ZERO LIFT ALPHA", "Radians" },
        };
    }
}
